name: Terraform automation pipeline

on:
    push:
        branches:
            - master

    # pull_request:
    #     branches:
    #         - master

    workflow_dispatch:

jobs:
    terraform-plan:
        defaults:
            run:
                working-directory: terraform

        runs-on: ubuntu-latest
        steps:
            - name: Clone github repo
              uses: actions/checkout@v4
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.12.2
            - name: Terraform init
              run: terraform init

            - name: Terraform validate
              run: terraform validate

            - name: Terraform format
              run: terraform fmt -check

            - name: Terraform plan
              run: terraform plan

    terraform-apply:
        if: github.ref == 'refs/heads/master'
        needs: terraform-plan

        environment:
            name: production

        defaults:
            run:
                working-directory: terraform
        runs-on: ubuntu-latest

        outputs:
            vpc_id: ${{ steps.tf_outputs.outputs.vpc_id}}
        steps:
            - name: Clone repo
              uses: actions/checkout@v4
            - name: aws configure
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.12.2
            - name: Initialize terraform
              run: terraform init
            - name: Terraform Apply
              run: terraform apply -auto-approve
            - name: Get terraform output
              id: tf_outputs
              run: |
                  echo "vpc_id=$(terraform output -raw vpc_id)" >> $GITHUB_OUTPUT

    helm:
        if: github.ref == 'refs/heads/master'
        needs: terraform-apply
        runs-on: ubuntu-latest
        environment:
            name: production
        env:
            VPC_ID: ${{ needs.terraform-apply.outputs.vpc_id }}
        steps:
            - name: Clone repo
              uses: actions/checkout@v4
            - name: aws configure
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1
            - name: install helm
              uses: azure/setup-helm@v5.0.0
              with:
                  version: latest
            - name: Install kubectl
              uses: azure/setup-kubectl@v4
              with:
                  version: "v1.29.0"
            - name: Update kubeconfig
              run: aws eks update-kubeconfig --region ap-south-1 --name jerney-eks-cluster
            - name: Verify cluster connectivity
              run: kubectl get nodes
            - name: Create kube-system namespace if missing
              run: kubectl create namespace kube-system --dry-run=client -o yaml | kubectl apply -f -
            - name: Install alb controller
              run: |
                  helm repo add eks https://aws.github.io/eks-charts
                  helm repo update

                  helm upgrade --install aws-load-balancer-controller \
                  eks/aws-load-balancer-controller \
                  -n kube-system \
                  -f helm/alb-controller-values.yaml \
                  --set vpcId=${VPC_ID} \
                  --wait
            - name: Wait for ALB controller
              run: kubectl rollout status deployment/aws-load-balancer-controller -n kube-system --timeout=5m

            - name: Helm deploy Application
              run: helm upgrade --install jerney ./helm/jerney-app --namespace jerney --create-namespace --wait --timeout 10m
